# ==========================================
# NGOConnect++ AI - Eureka Server
# ==========================================

spring.application.name=eureka-server

server.port=8761

# Eureka instance
eureka.instance.hostname=localhost

# Standalone Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka endpoint
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Eureka Server settings
eureka.server.enable-self-preservation=true
